### ISSUE TITLE
Files.move() causes DirectoryNotEmptyException when running in Docker container

### ISSUE THREAD

**Issue by ponchofiesta** [tuub/kitodo-mediaserver#108]
When the importer runs in Docker for some reason `Files.move()` doesn't work:

```
2018-07-04 15:56:34 [main] ERROR org.kitodo.mediaserver.importer.control.ImporterFlowControl - An error occured importing work UATUB_717-0102, Error: java.nio.file.DirectoryNotEmptyException: /srv/kitodo/mediaserver/importing/UATUB_717-0102
java.nio.file.DirectoryNotEmptyException: /srv/kitodo/mediaserver/importing/UATUB_717-0102
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:498)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.kitodo.mediaserver.importer.control.ImporterFlowControl.importWorks(ImporterFlowControl.java:172)
...
```

But the work was moved to *importing* successfully. This was done by `FileUtils.moveDirectory()` in `ImporterUtils`.

So changing this:
```
Files.move(
    workDir.toPath(),
    Paths.get(newWork.getPath())
);
```
to this:
```
FileUtils.moveDirectory(workDir, new File(newWork.getPath()));
```
works.

**Comment by ponchofiesta** [comment]
In `ImporterFlowControl` for all directory moves I replaced `Files.move()` by `FileUtils.moveDirectory()`.
